### ISSUE TITLE
source_gen ^2.0.0

### ISSUE THREAD

**Issue by HudsonAfonso** [petercinibulk/envied#125]
source_gen ^2.0.0

**Comment by jpeiffer** [comment]
FYI, it requires Dart 3.6.0.  So if applied to this package, the range of supported Dart / Flutter versions would decrease significantly.  Might be worth waiting a bit since not everyone updates Flutter immediately, or at least deploy it as a new "breaking change" major version.

**Comment by HudsonAfonso** [comment]
First, thanks for your work and time

I see, maybe you can release it as a Prerelease version?

**Comment by jpeiffer** [comment]
I'm not a maintainer, so my ability to deploy anything doesn't exist.

However, if you need this now, I saw that dependabot created a PR to do it and you can use a git ref against it:

```
dependencies:
  envied:
    git:
      url: https://github.com/petercinibulk/envied
      ref: dependabot/pub/packages/envied_generator/main/source_gen-2.0.0
```
