### ISSUE TITLE
Non-compiling v1.0.0

### ISSUE THREAD

**Issue by saropa** [petercinibulk/envied#129]
Hi, 

It looks like the current package source code has a partial implementation of a PR, namely the “environment” variable added to `envied_base.dart`.

I had to migrate this field over to the stable build to get it to compile:

``` dart
  /// for the constructor:   this.environment = false,

  /// Whether to read the ultimate values from [Platform.environment] rather
  /// than from the `.env` file.  When set to true, the value found in the
  /// `.env` file will not be used as the ultimate value but will instead be
  /// used as the key and the ultimate value will be read from
  /// [Platform.environment].
  final bool environment;
```
  
  Cheers,
  Saropa

**Comment by techouse** [comment]
Hey! I can't reproduce this error. I just tried using

```yaml
dependencies:
  envied: ^1.0.0

dev_dependencies:
  envied_generator: ^1.0.0

dependency_overrides:
  envied:
    git:
      url: https://github.com/petercinibulk/envied.git
      ref: main
      path: packages/envied
  envied_generator:
    git:
      url: https://github.com/petercinibulk/envied.git
      ref: main
      path: packages/envied_generator
```

and it compiles just fine
