### ISSUE TITLE
Uri and DateTime types support

### ISSUE THREAD

**Issue by imsamgarg** [petercinibulk/envied#23]
Hey,

How about adding support for Uri and Datetime types? Both types have their own parsing methods attach to them so it would not be difficult to add support for these type. Isn't it? Whats your opinion?

**Comment by eximius313** [comment]
I'd love to see Uri support as well

**Comment by techouse** [comment]
As a workaround, you can simply parse the strings yourself.

**Comment by techouse** [comment]
@eximius313 @imsamgarg would you mind testing #70 🙏

**Comment by eximius313** [comment]
Of course I don't mind! But it seems it's not released yet?

**Comment by techouse** [comment]
> Of course I don't mind! But it seems it's not released yet?

Nope. You'd have to reference the PR directly. :)

**Comment by eximius313** [comment]
umm.. how to do that?

**Comment by techouse** [comment]
> umm.. how to do that?

Using `dependency_overrides`, like so:

```yaml
dependency_overrides:
  envied:
    git:
      url: https://github.com/petercinibulk/envied
      ref: feat/uri-and-datetime-support
      path: packages/envied/
  envied_generator:
    git:
      url: https://github.com/petercinibulk/envied
      ref: feat/uri-and-datetime-support
      path: packages/envied_generator/
```
