### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by TArch64** [petercinibulk/envied#26]
Hi! I'm working on a little project and found an idea for improvement. Currently envied doesn't support using enums as an env type. Here is my use case:

I want to make an app env type strictly typed instead of any string but build envied gets me an error
```
Envied can only handle types such as `int`, `double`, `num`, `bool` and `String`. Type `AppEnv` is not one of them.
``` 

My code
```dart
// app_env.dart

enum AppEnv {
  staging,
  production;

  static AppEnv? fromString(String string) {
    return AppEnv.values.firstWhere((value) => value.name == string);
  }

  static AppEnv fromStringOrThrow(String string) {
    AppEnv? value =  AppEnv.fromString(string);
    assert(value != null, 'Unknown app env');
    return value!;
  }

  bool get isProduction => this == AppEnv.production;
  bool get isString => this == AppEnv.staging;
}
```

```dart
// env.dart
import 'package:envied/envied.dart';

import 'app_env.dart';

part 'env.g.dart';

@Envied(path: '.env')
abstract class Env {
  @EnviedField(varName: 'APP_HOST')
  static const appHost = _Env.appHost;

  @EnviedField(varName: 'APP_ENV')
  static final appEnv = AppEnv.fromStringOrThrow(_Env.appEnv);

  static String get _apiPrefix => appEnv.isProduction ? '' : appEnv.name;
  static String get apiEndpoint => 'https://$_apiPrefix.$appHost/graphql';
}
```

**Comment by TArch64** [comment]
As a workaround, i can do a private field with a string value but it would nice to have native enum support.

```dart
@EnviedField(varName: 'APP_ENV')
static const _appEnv = _Env._appEnv;
static final appEnv = AppEnv.fromStringOrThrow(_appEnv);
```

**Comment by techouse** [comment]
This one could be a bit more complicated. Also, we'd probably want to use [`byName`](https://api.dart.dev/stable/3.1.5/dart-core/EnumByName/byName.html) to lookup the values.

**Comment by techouse** [comment]
@TArch64 can you please test #73 by directly referencing the PR, i.e.

```yaml
dependency_overrides:
  envied:
    git:
      url: https://github.com/petercinibulk/envied
      ref: feat/enum
      path: packages/envied/
  envied_generator:
    git:
      url: https://github.com/petercinibulk/envied
      ref: feat/enum
      path: packages/envied_generator/
```
