### ISSUE TITLE
Environment variable not found for field

### ISSUE THREAD

**Issue by rignaneseleo** [petercinibulk/envied#84]
I'm using https://pub.dev/packages/dart_openai#api-key tutorial to set up my OpenAi key using envied.

### Setup

- **lib/env/.env**
`OPEN_AI_API_KEY=sk-cX....`

- **lib/env/env.dart**
```
// lib/env/env.dart
import 'package:envied/envied.dart';

part 'env.g.dart';

@Envied(path: ".env")
abstract class Env {
  @EnviedField(varName: 'OPEN_AI_API_KEY') // the .env variable.
  static final String apiKey = _Env.apiKey;
}
```

### Error

This is what I get when I run `flutter  pub run build_runner build --delete-conflicting-outputs`:

```
Environment variable not found for field `apiKey`.
package:parenthood/env/env.dart:9:23
  ╷
9 │   static final String apiKey = _Env.apiKey;
  │                       ^^^^^^
  ╵
```

I tried with:
- `flutter clean` before build_runner
- `dart run build_runner clean` before build_runner
- `dart run build_runner build` instead of pub run
- moving the `.env` file in the lib root
- using `static const apiKey` instead

Nothing worked.

### Environment

My `dev_dependencies`
```
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1
  # json_annotation: ^4.8.1
  freezed: ^2.4.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  envied_generator: ^0.5.2
```
