### ISSUE TITLE
What is builder name/key of envied generator?

### ISSUE THREAD

**Issue by geardy47** [petercinibulk/envied#85]
I want to specify build_runner config for certain purposes and set envied_generator to false, but I get this error.

```bash
[WARNING] Configuring `envied_generator:enviedBuilder` in target `projectname: projectname` but this is not a known Builder
```

This is my build.custom.yaml file. Would you tell me what is the `enviedBuilder` name actually? Thanks

```yaml
targets:
  $default:
    builders:
      mockito:mockBuilder:
        enabled: false
      envied_generator:enviedBuilder:
        enabled: false
```
