### ISSUE TITLE
Error when value has $

### ISSUE THREAD

**Issue by azliR** [petercinibulk/envied#94]
The output:
```
[SEVERE] envied_generator:envied on lib/configs/environment.dart:

Could not format because the source could not be parsed:

line 11, column 50 of .: Expected an identifier.
   ╷
11 │ static const String dbPassword = 'somestringwith$';
   │                                                  ^
   ╵
[INFO] Running build completed, took 62ms
[INFO] Caching finalized dependency graph completed, took 33ms
[SEVERE] Failed after 99ms
```
but when i change it to `somestringwith\$`, it worked.

**Comment by techouse** [comment]
Hi @azliR 

Can you please clarify if the value you have in your `.env` file contains a `$` in it, i.e.

```
DB_PASSWORD=somestring$
```

?

**Comment by techouse** [comment]
@azliR can you please test with this PR #95

**Comment by azliR** [comment]
> Hi @azliR 
> 
> Can you please clarify if the value you have in your `.env` file contains a `$` in it, i.e.
> 
> ```ini
> DB_PASSWORD=somestring$
> ```
> 
> and when you change it to
> 
> ```ini
> DB_PASSWORD=somestring\$
> ```
> 
> it worked?

Yess

**Comment by azliR** [comment]
> @azliR can you please test with this PR #95
> 
> ```yaml
> dependency_overrides:
>   envied:
>     git:
>       url: https://github.com/petercinibulk/envied
>       ref: 83466c8679cdbbc135f1d9802410764cf283f6ed
>       path: packages/envied/
>   envied_generator:
>     git:
>       url: https://github.com/petercinibulk/envied
>       ref: 83466c8679cdbbc135f1d9802410764cf283f6ed
>       path: packages/envied_generator/
> ```

Sure! Give me a minute

**Comment by azliR** [comment]
I don't know why it said success, but the `env.g.dart` is not generated.

**Comment by techouse** [comment]
Did you follow the directions in the PR description?

**Comment by azliR** [comment]
Yes, both with `@EnviedField(rawString: true)` and `@Envied(rawStrings: true)`

**Comment by techouse** [comment]
What if you try using the branch as the ref, i.e.

```yaml
dependency_overrides:
  envied:
    git:
      url: https://github.com/petercinibulk/envied
      ref: fix/issue-94-raw-strings
      path: packages/envied/
  envied_generator:
    git:
      url: https://github.com/petercinibulk/envied
      ref: fix/issue-94-raw-strings
      path: packages/envied_generator/
```
