### ISSUE TITLE
0.5.4 version fail to generate

### ISSUE THREAD

**Issue by RahnRazamai** [petercinibulk/envied#99]
I noticed latest version caused something like this to throw error **API_KEY=6690043050=** the '**=**' in the value is throwing error. Is it intended? if not can please help to fix?

Below is the error thrown
[SEVERE] envied_generator:envied on lib/keys.dart:

Bad state: Pattern matching error
package:envied_generator/src/parser.dart 42:5      Parser.parseOne
package:envied_generator/src/parser.dart 23:38     Parser.parse
package:envied_generator/src/load_envs.dart 24:17  loadEnvs
package:envied_generator/src/generator.dart 60:9   EnviedGenerator.generateForAnnotatedElement
package:source_gen/src/output_helpers.dart 10:1    normalizeGeneratorOutput
package:async/src/stream_completer.dart 76:3       StreamCompleter.setSourceStream

**Comment by knottx** [comment]
facing same issue. now I'm roll back to version 0.5.3

**Comment by techouse** [comment]
Hi,

Just to clarify, your key is
```ini
API_KEY=6690043050=
```
?

**Comment by knottx** [comment]
> Hi,
> 
> Just to clarify, your key is
> 
> ```ini
> API_KEY=6690043050=
> ```
> 
> ?
> 
> EDIT: I have just implemented a fix in #100. Would you mind checking it out and reporting back any findings?

My key is 
```properties
URL_001=https://my.example.com/path/to/my/file.mp4?param1=value1&param2=value2
```

**Comment by techouse** [comment]
@knottx @RahnRazamai can you both please test with #100 by adding these dependency overrides to your pubspec.yaml

```yaml
dependency_overrides:
  envied:
    git:
      url: https://github.com/petercinibulk/envied.git
      ref: fix/issue-99-double-equal-sign
      path: packages/envied
  envied_generator:
    git:
      url: https://github.com/petercinibulk/envied.git
      ref: fix/issue-99-double-equal-sign
      path: packages/envied_generator
```
